[package]
name = "rust_cascade"
description = "A simple mmh3 based bloom filter cascade implementation in Rust."
license-file = "license.txt"
version = "0.1.1"
authors = ["Mark Goodwin <mgoodwin@mozilla.com>"]

[dependencies]
murmurhash3="0.0.5"
bitvec="0.10.0"
byteorder="1.3.1"
rand="0.6.5"
digest="0.8.0"