[package]
name = "rust_cascade"
description = "A simple mmh3 based bloom filter cascade implementation in Rust."
license = "MPL-2.0"
license-file = "license.txt"
version = "0.1.0"
authors = ["Mark Goodwin <mgoodwin@mozilla.com>"]

[dependencies]
murmurhash3="*"
bitvec="*"
byteorder="*"
rand="*"
digest="*"