[package]
name = "rust_cascade"
description = "A simple mmh3 based bloom filter cascade implementation in Rust."
license = "MPL-2.0"
version = "0.3.2"
authors = ["Mark Goodwin <mgoodwin@mozilla.com>"]

[dependencies]
murmurhash3="0.0.5"
bitvec = "0.10"
byteorder="1.3.1"
rand="0.*"
digest="0.8.0"

[patch.crates-io]
bitvec = { path = "lib/bitvec", version = "0.10.0" }
